### ISSUE TITLE
GLPI 10

### ISSUE THREAD

**Issue by nelero** [Digitemis/GLPIScan#7]
Hi,
thanks for your tool !
Did you plan to push it compatible with GLPI 10 and newer ?
thanks

**Comment by Digitemis** [comment]
Hello,
A new version compatible with GLPI10 will be released this week.
It also fix some recent bugs.
Regards,

Digitemis.

**Comment by Digitemis** [comment]
New release : https://github.com/Digitemis/GLPIScan/commit/0fd1499331464492512053ac35fd40545c787dd8
